### ISSUE TITLE
Launch email

### ISSUE THREAD

**Issue by vanderlin** [vanderlin/halp#21]
lets make a launch email to send to the office about "Halp" like a invite email.

**Comment by kjmiller1029** [comment]
Attempt at content for this... what am I missing?

------------

![screen shot 2015-07-28 at 8 14 47 am](https://cloud.githubusercontent.com/assets/2963439/8930973/badb7b2c-3500-11e5-929c-991ff980a651.png)

**You're Invited to Halp!**
Halp is a task board for our studio. It connects willing volunteers to folks who need help with anything from proofreading a deck to moving a couch. If you're between projects, it's a great place to find small-scale tasks to experiment with new skills. To get started, log in with your IDEO e-mail credentials, and Halp will notify you whenever a new task is created. 

[LOG IN TO HALP]

**Comment by kjmiller1029** [comment]
![welcome-email](https://cloud.githubusercontent.com/assets/2963439/8931457/741ec51e-3504-11e5-89b3-987ef57b1845.png)

**Comment by kjmiller1029** [comment]
![intro-email](https://cloud.githubusercontent.com/assets/2963439/8932288/2151b2f0-350a-11e5-92dd-60fe892d4291.png)
