### ISSUE TITLE
Welcome (first email)

### ISSUE THREAD

**Issue by vanderlin** [vanderlin/halp#22]
Email when someone first connects

**Comment by kjmiller1029** [comment]
![welcome-email](https://cloud.githubusercontent.com/assets/2963439/8932262/fa7cac7a-3509-11e5-95bc-a66f6317cf9e.png)

**Comment by kjmiller1029** [comment]
![welcome-email](https://cloud.githubusercontent.com/assets/2963439/8932273/0b1acb16-350a-11e5-9077-9e9438fe73bc.png)
